canteen/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('canteen_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

canteen_app/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'canteen_app'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='canteen_app/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='canteen_app/logout.html'), name='logout'),
    path('menumain/', views.category, name='menumain'),
    path('menu/<int:food_type_id>/', views.menu_list, name='menu_list'),
    path('bill/', views.bill, name='bill'),
    path('menu1/<int:menu_id>/', views.cart, name='cart'),
    path('orders_list/', views.orders_list, name='order'),
    path('orders_list1/<int:order_id>/', views.full_fill, name='fulfill'),

    path('home/', views.home, name="home"),
    path('about/', views.about, name="about"),
    path('gallery/', views.gallery, name="gallery"),
    path('form/', views.form, name="form"),
    path('form/food/', views.food, name="food"),
]

canteen_app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):

    phone = models.CharField(max_length=12, blank=True)


class FoodType(models.Model):

    food_type = models.CharField(max_length=100)
    image = models.FileField(null=True)

    def __str__(self):
        return self.food_type


class Menu(models.Model):

    food_type = models.ForeignKey(FoodType, on_delete=models.CASCADE)
    food_name = models.CharField(max_length=100)
    price = models.PositiveSmallIntegerField()

    def __str__(self):
        return self.food_name


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_fulfilled = models.BooleanField(default=False)
    total_price = models.PositiveSmallIntegerField()


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    food_item = models.ForeignKey(Menu, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField()

canteen_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User

class SignUpForm(UserCreationForm):

    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=30, required=False)
    email = forms.EmailField(max_length=254)
    phone = forms.CharField(max_length=12, required=False)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'phone', 'password1', 'password2', )

canteen_app/views.py
from django.shortcuts import render
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect
from .forms import *
from .models import *
from canteen.settings import MEDIA_URL

# Create your views here.
def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/home/')
    else:
        form = SignUpForm()
    return render(request, 'canteen_app/signup.html', {'form': form})


def category(request):
    food_types = FoodType.objects.all()
    return render(request, 'canteen_app/menumain.html', {'food_types':food_types, 'media_url':MEDIA_URL})


def menu_list(request, food_type_id):
    menu_food = Menu.objects.filter(food_type_id=food_type_id)
    return render(request, 'canteen_app/menu_list.html', {'menu_food':menu_food})


def cart(request, menu_id):
    orders = Order.objects.filter(user=request.user, is_fulfilled=False)
    menu = Menu.objects.filter(id=menu_id)
    if len(orders)==0:
        order = Order(user=request.user, is_fulfilled=False, total_price=menu[0].price)
        order.save()
        order_item = OrderItem(order=order, food_item=menu[0], quantity=1)
        order_item.save()
    else:
        orders[0].total_price += menu[0].price
        orders[0].save()
        order_item = OrderItem(order=orders[0], food_item=menu[0], quantity=1)
        order_item.save()
    menu_food = Menu.objects.filter(food_type_id=menu[0].food_type_id)
    return render(request, 'canteen_app/menu_list.html', {'menu_food':menu_food})


def bill(request):
    orders = Order.objects.filter(user=request.user, is_fulfilled=False)
    bill_items = OrderItem.objects.filter(order=orders[0])
    return render(request, 'canteen_app/bill.html', {'bill_items':bill_items, 'order':orders[0]})


def orders_list(request):
    orders = Order.objects.filter(is_fulfilled=False)
    li = []
    for order in orders:
        dire = {}
        li2 = []
        order_items = OrderItem.objects.filter(order=order)
        for order_item in order_items:
            li2.append(order_item.food_item.food_name)
        food_types = li2
        dire['id'] = order.id
        dire['user'] = order.user.username
        dire['food_items'] = food_types
        dire['total_price'] = order.total_price
        li.append(dire)
    return render(request, 'canteen_app/orders_list.html', {'orders': li})

def full_fill(request, order_id):
    order = Order.objects.get(id=order_id)
    order.is_fulfilled = True
    order.save()
    #return redirect(to=orders_list)
    orders = Order.objects.filter(is_fulfilled=False)
    li = []
    for order in orders:
        dire = {}
        li2 = []
        order_items = OrderItem.objects.filter(order=order)
        for order_item in order_items:
            li2.append(order_item.food_item.food_name)
        food_types = li2
        dire['id'] = order.id
        dire['user'] = order.user.username
        dire['food_items'] = food_types
        dire['total_price'] = order.total_price
        li.append(dire)
    return render(request, 'canteen_app/orders_list.html', {'orders': li})



def home(request):
    return render(request, 'canteen_app/home.html')


def about(request):
    return render(request, 'canteen_app/about.html')


def gallery(request):
    return render(request, 'canteen_app/gallery.html')


def form(request):
    return render(request, 'canteen_app/forms.html')


def food(request):
    name = request.POST['foodname']
    file = request.FILES['file']
    foodname = FoodType(food_type=name, image=file)
    foodname.save()

    return render(request, 'canteen_app/forms.html')
    # return redirect(to, form) 

canteen_app/templates/canteen_app/bill.html
<!DOCTYPE html>
<html lang="en">
<head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Inline_Form</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" 
              crossorigin="anonymous">
              <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" 
              integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
              crossorigin="anonymous">
              <style>
                 .col-4{
                  border: 2px grey;
                  border-radius: 30%;
                } 
                #one,#two{
                  margin: 10px;
                }
                a{
                color: #ffffff;
                } 
               .order-button{
                   align-self: center;
               }
              </style>
    
</head>
<body>
    <form class="form-inline">
            {% for item in bill_items %}
            <label for="inlineFormInputName2" class="col-4" id="one">{{ item.food_item.food_name }}</label>
            <label for="inlineFormInputGroupUsername2" class="col-4" id="two">{{ item.food_item.price }}</label>
            {% endfor %}
        <!-- <input type="text" class="form-control mb-2 mr-sm-2" id="inlineFormInputName2" placeholder="Food_Name">
        -->
        
        <!-- <div class="input-group mb-2 mr-sm-2">
            <div class="input-group-prepend">
            <div class="input-group-text">@</div>
            </div>
            <input type="text" class="form-control" id="inlineFormInputGroupUsername2" placeholder="">
        </div>
        -->
        <!-- <div class="form-check mb-2 mr-sm-2">
            <input class="form-check-input" type="checkbox" id="inlineFormCheck">
            <label class="form-check-label" for="inlineFormCheck">
            Remember me
            </label>
        </div> -->
        </form>
        <hr style="border:1px dotted black;"/>
        <div class='total-price'>
                <label for="inlineFormInputName2" class="col-4" id="one">Total Price : {{ order.total_price }}</label>
        </div>
        <div class='order-button'>
            <button type="submit" class="btn btn-primary mb-2 ">
                <a href="{% url 'canteen_app:menumain' %}" color=rgb(255,0,0)>Confirm</a>
            </button>
        </div>
</body>
</html>

canteen_app/templates/canteen_app/forms.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Form</title>
  </head>
  <body>

    <form method="post" action="{% url 'canteen_app:food' %}" enctype="multipart/form-data">
      {% csrf_token %}
          <div class="form-group">
            <label for="">Name</label>
            <input type="text" name="foodname" class="form-control" placeholder="Name of food" >
            <label >Image</label>
            <input type="file" name="file" class="form-control-file" >
              <button type="submit" class="btn btn-primary m-1"> Submit</button>
          </div>
    </form>
    <!--{% if uploaded_file_url %}-->
      <!--<p>File uploaded at: <a href="{{ uploaded_file_url }}">{{ uploaded_file_url }}</a></p>-->
    <!--{% endif %}-->
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

canteen_app/templates/canteen_app/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<title>Food Club a Hotels and Restaurants Category Bootstrap responsive Website Template | Home </title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta charset="utf-8">
<meta name="keywords" content="Food Club Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- bootstrap-css -->
<link href='{% static "canteen_app/css/bootstrap.css" %}' rel="stylesheet" type="text/css" media="all" />
<!--// bootstrap-css -->
<!-- css -->
<link rel="stylesheet" href='{% static "canteen_app/css/style.css" %}' type="text/css" media="all" />
<!--// css -->
<!-- font-awesome icons -->
<link href='{%static "canteen_app/css/font-awesome.css"%}' rel="stylesheet">
<!-- //font-awesome icons -->
<!-- font -->
<link href="//fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i" rel="stylesheet">
<link href="//fonts.googleapis.com/css?family=Great+Vibes&amp;subset=latin-ext" rel="stylesheet">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
<!-- //font -->
<script src='{% static "canteen_app/js/jquery-1.11.1.min.js" %}'></script>
<script src='{% static "canteen_app/js/bootstrap.js" %}'></script>
<script type="text/javascript">
	jQuery(document).ready(function($) {
		$(".scroll").click(function(event){
			event.preventDefault();
			$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
		});
	});
</script>

<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
<![endif]-->
</head>
<body>
	<!-- banner -->
	<div class="banner jarallax">

		<!-- agileinfo-dot -->
		<div class="agileinfo-dot">
			<div class="w3layouts-header-top">
				<div class="w3-header-top-grids">
					<div class="w3-header-top-left">
						<p><i class="fa fa-volume-control-phone" aria-hidden="true"></i> +91 234 567 8901</p>
					</div>
					<div class="w3-header-top-right">
						<div class="agileinfo-social-grids">
							<ul>
								<li><a href="#"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a href="#"><i class="fa fa-rss"></i></a></li>
								<li><a href="#"><i class="fa fa-vk"></i></a></li>
							</ul>
						</div>
						<div class="w3-header-top-right-text">
							<p><i class="fa fa-home" aria-hidden="true"></i> 1st Street , Andheri west</p>
						</div>
						<div class="clearfix"> </div>
					</div>
					<div class="clearfix"> </div>
				</div>
			</div>
			<div class="head">
				<div class="head-nav-grids">
					<div class="navbar-top">
							<!-- Brand and toggle get grouped for better mobile display -->
							<div class="navbar-header">
							  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							  </button>
								 <div class="navbar-brand logo ">
									<h1><a href='{% url "canteen_app:home" %}'>Food <span>Club</span></a></h1>
								</div>

							</div>

							<!-- Collect the nav links, forms, and other content for toggling -->
							<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
							 <ul class="nav navbar-nav link-effect-4">
							<li {% block home %}  {% endblock %}><a href='{% url "canteen_app:home" %}' data-hover="Home">Home</a> </li>
								<li {% block about %}  {% endblock %}><a href='{% url "canteen_app:about" %}' data-hover="About">About </a> </li>
								<li {% block gallery %}  {% endblock %}><a href='{% url "canteen_app:gallery" %}'  data-hover="Gallery">Gallery</a></li>
								<li {% block menu %}  {% endblock %}><a href='{% url "canteen_app:menumain" %}'  data-hover="Menu">Menu</a></li>
								<!--<li class="dropdown">-->
									<!--<a href="codes.html" class="dropdown-toggle" data-hover="Pages" data-toggle="dropdown">Pages <b class="caret"></b></a>-->
									<!--<ul class="dropdown-menu">-->
										<!--<li><a href="icons.html">Icons</a></li>-->
										<!--<li><a href="codes.html">Short Codes</a></li>-->
									<!--</ul>-->
							  <!--</li>-->
								<!--<li><a href="contact.html" data-hover="Contact">Contact</a></li>-->
							  </ul>
							</div><!-- /.navbar-collapse -->
						</div>

					<div class="header-left">
						<ul>
							<li><i class="fa fa-envelope" aria-hidden="true"></i> <a href="https://mail.google.com/mail/u/0/#inbox?compose=CllgCJZcRKJkhjXWprcWFzjZRWFhBCNLjWBJrTqqMnKPKfvRLmTNCMtrSZStXMKJDmPSBTzsxRL">amanpatwa999@gmail.com</a></li>
							<li><i class="fa fa-fax" aria-hidden="true"></i> +91 234567892</li>
						</ul>
					</div>
					<div class="clearfix"></div>
				</div>
			</div>
			{% block title %}
			<div class="w3layouts-banner-slider">
				<div class="w3layouts-banner-top-slider">
					<div class="slider">
						<div class="callbacks_container">
							<ul class="rslides callbacks callbacks1" id="slider4">
								<li>
									<div class="agileits-banner-info">
										<h3>One cannot <span>think well, love well, sleep well, if one has not dined well.</span></h3>
										<!--<div class="w3-button">-->
											<!--<a href="single.html">More</a>-->
										<!--</div>-->
									</div>
								</li>
								<li>
									<div class="agileits-banner-info">
										<h3>Pull up a chair. <span>Take a taste. Come join us. Life is so endlessly delicious. </span></h3>
										<!--<div class="w3-button">-->
											<!--<a href="single.html">More</a>-->
										<!--</div>-->
									</div>
								</li>
							</ul>
						</div>
						<div class="clearfix"> </div>
						<script src='{% static "canteen/js/responsiveslides.min.js" %}'></script>
						<script>
							// You can also use "$(window).load(function() {"
							$(function () {
							  // Slideshow 4
							  $("#slider4").responsiveSlides({
								auto: true,
								pager:true,
								nav:true,
								speed: 500,
								namespace: "callbacks",
								before: function () {
								  $('.events').append("<li>before event fired.</li>");
								},
								after: function () {
								  $('.events').append("<li>after event fired.</li>");
								}
							  });

							});
						 </script>
						<!--banner Slider starts Here-->
					</div>
				</div>
			</div>
			{% endblock %}
		</div>
		<!-- //agileinfo-dot -->
	</div>
	<!-- //banner -->

    {% block body %}
    {% endblock %}


    <!-- footer -->
	<div class="w3-agile-footer">
		<div class="container">
			<div class="footer-grids">
				<div class="col-md-4 footer-grid">
					<div class="footer-grid-heading">
						<h3><a href='{% url "canteen_app:home" %}'>Food <span>Club</span></a></h3>
					</div>
					<div class="agile-footer-info">
						<p>Maecenas pharetra scelerisque sem quis commodo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Interdum et malesuada fames ac ante ipsum primis in faucibus.</p>
					</div>
					<div class="social">
						<ul>
							<li><a href="#"><i class="fa fa-facebook"></i></a></li>
							<li><a href="#"><i class="fa fa-twitter"></i></a></li>
							<li><a href="#"><i class="fa fa-rss"></i></a></li>
							<li><a href="#"><i class="fa fa-vk"></i></a></li>
						</ul>
					</div>
				</div>
				<div class="col-md-4 footer-grid">
					<div class="footer-grid-heading">
						<h4>Address</h4>
					</div>
					<div class="footer-grid-info">
						<p>Eiusmod Tempor inc
							<span>St Dolore Place,Kingsport 56777.</span>
						</p>
						<p class="phone">Phone : +91 23 456 7892
							<span>Email : <a href="https://mail.google.com/mail/u/0/#inbox?compose=CllgCJZcRKJkhjXWprcWFzjZRWFhBCNLjWBJrTqqMnKPKfvRLmTNCMtrSZStXMKJDmPSBTzsxRL">amanpatwa999@gmail.com</a></span>
							<span>FAX : 123 456 7890</span>
						</p>
					</div>
				</div>
				<div class="col-md-4 footer-grid">
					<div class="footer-grid-heading">
						<h4>Navigation</h4>
					</div>
					<div class="footer-grid-info">
						<ul>
							<li><a href='{% url "canteen_app:home" %}'>Home</a></li>
							<li><a href='{% url "canteen_app:about" %}'>About</a></li>
							<li><a href='{% url "canteen_app:gallery" %}'>Gallery</a></li>
							<!--<li><a href="icons.html">Icons</a></li>-->
							<!--<li><a href="codes.html">Short Codes</a></li>-->
							<!--<li><a href="contact.html">Contact</a></li>-->
						</ul>
					</div>
				</div>
				<!--<div class="col-md-3 footer-grid">-->
					<!--<div class="footer-grid-heading">-->
						<!--<h4>Twitter Posts</h4>-->
					<!--</div>-->
					<!--<div class="agile-footer-grid">-->
						<!--<ul class="w3agile_footer_grid_list">-->
							<!--<li>Ut aut reiciendis voluptatibus maiores <a href="#">http://example.com</a> alias, ut aut reiciendis.-->
								<!--<span><i class="fa fa-twitter" aria-hidden="true"></i> 02 days ago</span></li>-->
							<!--<li>Itaque earum rerum hic tenetur a sapiente delectus <a href="#">http://example.com</a><span><i class="fa fa-twitter" aria-hidden="true"></i> 03 days ago</span></li>-->
						<!--</ul>-->
					<!--</div>-->
				<!--</div>-->
				<div class="clearfix"> </div>
			</div>
			<div class="agileits-w3layouts-copyright">
				<p>© 2019 Food Club . All Rights Reserved | Design by <a href="#"> Aman</a> </p>
			</div>
		</div>
	</div>
	<!-- //footer -->
	<script src='{% static "canteen_app/js/jarallax.js" %}'></script>
	<script src='{% static "canteen_app/js/SmoothScroll.min.js" %}'></script>
	<script type="text/javascript">
		/* init Jarallax */
		$('.jarallax').jarallax({
			speed: 0.5,
			imgWidth: 1366,
			imgHeight: 768
		})
	</script>
	<script type="text/javascript" src='{% static "canteen_app/js/move-top.js" %}'></script>
	<script type="text/javascript" src='{% static "canteen_app/js/easing.js" %}'></script>
	<!-- here stars scrolling icon -->
	<script type="text/javascript">
		$(document).ready(function() {
			/*
				var defaults = {
				containerID: 'toTop', // fading element id
				containerHoverID: 'toTopHover', // fading element hover id
				scrollSpeed: 1200,
				easingType: 'linear'
				};
			*/

			$().UItoTop({ easingType: 'easeOutQuart' });

			});
	</script>
	<!-- //here ends scrolling icon -->
</body>
</html>

canteen_app/templates/canteen_app/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>LOGIN</title>
    <link rel="stylesheet" href="own.css" type="text/css">
    <link rel="stylesheet" href="bootstrap.css" type="text/css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
  <div class="container-fluid bg">
    <div class="row">
      <div class="col-md-4 col-sm-4 col-xs-12"></div>
        <div class="col-md-4 col-sm-4 col-xs-12">
          <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Login</button>
          </form>
        </div>
      </div>
    </div>
  </body>
</html>

canteen_app/templates/canteen_app/menu_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Inline_Form</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" 
          crossorigin="anonymous">
          <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" 
          integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
          crossorigin="anonymous">
          <style>
             .col-4{
              border: 2px grey;
              border-radius: 30%;
            } 
            #one,#two{
              margin: 10px;
            }
            a{
            color: #ffffff;
            } 
           .order-button{
               align-self: center;
           }
          </style>
</head>
<body>
    <form class="form-inline">
          {% for food in menu_food %}
          <label for="inlineFormInputName2" class="col-4" id="one">{{ food.food_name }}</label>
          <label for="inlineFormInputGroupUsername2" class="col-4" id="two">{{ food.price }}</label>
          <button type="submit" class="btn btn-primary mb-2 ">
              <i class="fa fa-cart-plus" aria-hidden="true"></i>
              <a href="{% url 'canteen_app:cart' menu_id=food.id %}" color=rgb(255,0,0)>Add</a>
          </button>
          {% endfor %}
        <!-- <input type="text" class="form-control mb-2 mr-sm-2" id="inlineFormInputName2" placeholder="Food_Name">
       -->
        
        <!-- <div class="input-group mb-2 mr-sm-2">
          <div class="input-group-prepend">
            <div class="input-group-text">@</div>
          </div>
          <input type="text" class="form-control" id="inlineFormInputGroupUsername2" placeholder="">
        </div>
       -->
        <!-- <div class="form-check mb-2 mr-sm-2">
          <input class="form-check-input" type="checkbox" id="inlineFormCheck">
          <label class="form-check-label" for="inlineFormCheck">
            Remember me
          </label>
        </div> -->
     </form>
     <hr style="border:1px dotted black;"/>
     <div class='order-button'>
        <button type="submit" class="btn btn-primary mb-2 ">
            <a href="{% url 'canteen_app:bill' %}" color=rgb(255,0,0)>Order</a>
        </button>
        <button type="submit" class="btn btn-primary mb-2 ">
                <a href="{% url 'canteen_app:home' %}" color=rgb(255,0,0)>Back</a>
        </button>   
     </div>
</body>
</html>